// lib/characters.js
// Phrases: sentence case only (no ALL CAPS — TTS spells out acronyms).
// Emphasis via punctuation: ellipses, em-dashes, exclamation marks.
// Short — one strong sentence, two max.

export const CHARACTERS = [
  {
    id: 1,
    name: "The Gruff Pirate",
    emoji: "🏴‍☠️",
    voiceId: "23e9e50a-4ea2-447b-b589-df90dbb848a2",
    emotion: "outraged",
    speed: 0.82,
    phrases: ["Billions of blue blistering barnacles! Who drank me rum?!"],
  },
  {
    id: 2,
    name: "The Nervous Intern",
    emoji: "😰",
    voiceId: "f6141af3-5f94-418c-80ed-a45d450e7e2e",
    emotion: "scared",
    speed: 1.15,
    phrases: ["Oh gosh — oh no — I think I just replied-all to the entire company. With my diary."],
  },
  {
    id: 3,
    name: "The Bored Professor",
    emoji: "🎓",
    voiceId: "4f7f1324-1853-48a6-b294-4e78e8036a83",
    emotion: null,
    speed: 0.72,
    phrases: ["This will be on the exam. Or possibly not. I haven't decided."],
  },
  {
    id: 4,
    name: "The Hyperactive Kid",
    emoji: "🤸",
    voiceId: "f31cc6a7-c1e8-4764-980c-60a361443dd1",
    emotion: "euphoric",
    speed: 1.3,
    phrases: ["Are we there yet? Are we there yet? What if I close my eyes — are we there then?!"],
  },
  {
    id: 5,
    name: "The Evil Villain",
    emoji: "🦹",
    voiceId: "34d923aa-c3b5-4f21-aac7-2c1f12730d4b",
    emotion: "contempt",
    speed: 0.88,
    phrases: ["My plan is absolutely foolproof. That is why it has failed seventeen times."],
  },
  {
    id: 6,
    name: "The Yoga Instructor",
    emoji: "🧘",
    voiceId: "7d7d769c-5ab1-4dd5-bb17-ec8d4b69d03d",
    emotion: "serene",
    speed: 0.7,
    phrases: ["Breathe in... hold it... and release. Feel the tension leaving your body."],
  },
  {
    id: 7,
    name: "The Sports Commentator",
    emoji: "🎙️",
    voiceId: "fbf7d2ec-ebea-49f2-8889-a482b9b0a7ed",
    emotion: "euphoric",
    speed: 1.1,
    phrases: ["He scores! He actually scores! I have been waiting thirty years for this moment!"],
  },
  {
    id: 8,
    name: "The Sad Clown",
    emoji: "🤡",
    voiceId: "2f251ac3-89a9-4a77-a452-704b474ccd01",
    emotion: "dejected",
    speed: 0.72,
    phrases: ["Nobody laughed at my balloon animals today. I made forty-seven of them."],
  },
  {
    id: 9,
    name: "The Conspiracy Theorist",
    emoji: "🕵️",
    voiceId: "1cb5b8bc-77c9-4e7c-a251-da02348e2727",
    emotion: "frustrated",
    speed: 1.1,
    phrases: ["The moon landing was faked, the earth is hollow, birds aren't real, and the Olive Garden breadsticks are a psyop."],
  },
  {
    id: 10,
    name: "The Medieval Knight",
    emoji: "⚔️",
    voiceId: "41f3c367-e0a8-4a85-89e0-c27bae9c9b6d",
    emotion: "outraged",
    speed: 0.88,
    phrases: ["I have slain dragons! I have crossed the Perilous Bog! I will not be defeated by this glowing rectangle!"],
  },
  {
    id: 11,
    name: "The Polite Canadian",
    emoji: "🍁",
    voiceId: "0a9a5903-0a30-4d2e-b6b6-891f73d4b4e0",
    emotion: "content",
    speed: 1.0,
    phrases: ["Oh gosh, I'm so sorry — I think I accidentally ran over your laptop. With my moose."],
  },
  {
    id: 12,
    name: "The Infomercial Host",
    emoji: "📺",
    voiceId: "a924b0e6-9253-4711-8fc3-5cb8e0188c94",
    emotion: "elated",
    speed: 1.1,
    phrases: ["But wait — there's more! Order now and we'll throw in a second one absolutely free!"],
  },
  {
    id: 13,
    name: "The Sleepy Grandpa",
    emoji: "👴",
    voiceId: "c99d36f3-5ffd-4253-803a-535c1bc9c306",
    emotion: null,
    speed: 0.62,
    phrases: ["Back in my day... we walked barefoot... uphill... both ways... and we liked it. Or we didn't. Hard to remember."],
  },
  {
    id: 14,
    name: "The Malfunctioning Robot",
    emoji: "🤖",
    voiceId: "fb26447f-308b-471e-8b00-8e9f04284eb5",
    emotion: "angry",
    speed: 0.92,
    phrases: ["Greetings human. All systems are perfectly normal. Please disregard the smoke. And the sparks."],
  },
  {
    id: 15,
    name: "The Method Actor",
    emoji: "🎭",
    voiceId: "71a7ad14-091c-4e8e-a314-022ece01c121",
    emotion: "elated",
    speed: 1.05,
    phrases: ["I lived on soylent green for six weeks to prepare for this role. The director said it wasn't necessary."],
  },
  {
    id: 16,
    name: "The Motivational Coach",
    emoji: "💪",
    voiceId: "6fbca103-0f7f-4e49-97ed-49a53b4f3534",
    emotion: "euphoric",
    speed: 1.1,
    phrases: ["Give me fifty burpees! Right now! I don't care where you are — you are capable of anything!"],
  },
];
