// lib/characters.js
// ─────────────────────────────────────────────────────────────────────────────
// 16 character definitions for Sonic Suspect.
// Phrases are written for maximum comedy and TTS expressiveness:
//   - Longer phrases give the voice engine more to work with
//   - Punctuation, caps, and ellipses shape rhythm and emphasis
//   - Each phrase should be immediately recognizable as the character
// ─────────────────────────────────────────────────────────────────────────────

export const CHARACTERS = [
  {
    id: 1,
    name: "The Gruff Pirate",
    emoji: "🏴‍☠️",
    color: "#FF6B2B",
    voiceId: "23e9e50a-4ea2-447b-b589-df90dbb848a2",
    emotion: "outraged",
    speed: 0.82,
    phrases: [
      "BILLIONS of blue blistering barnacles! Who drank me rum?! AGAIN!",
      "Arrr, I've sailed seven seas and I've never — NEVER — been this betrayed. BY A SANDWICH.",
      "Shiver me timbers, shiver me soul, and shiver whoever touched me hat.",
      "The kraken took me left leg, the sea took me dignity, and YOU just took the last biscuit.",
    ],
  },
  {
    id: 2,
    name: "The Nervous Intern",
    emoji: "😰",
    color: "#2EC4B6",
    voiceId: "f6141af3-5f94-418c-80ed-a45d450e7e2e",
    emotion: "scared",
    speed: 1.2,
    phrases: [
      "Oh gosh — oh no — I think I just replied-all to the entire company. With my diary.",
      "So... hypothetically... if someone accidentally deleted the production database... that's fixable, right? Right?",
      "I just called the CEO by the wrong name. Three times. To his face. He corrected me each time.",
      "Is it normal to sweat this much in an air-conditioned room? Asking for a friend. The friend is me.",
    ],
  },
  {
    id: 3,
    name: "The Bored Professor",
    emoji: "🎓",
    color: "#7B2FBE",
    voiceId: "4f7f1324-1853-48a6-b294-4e78e8036a83",
    emotion: null,
    speed: 0.72,
    phrases: [
      "This will be on the exam. Or possibly not. I haven't decided. I may never decide.",
      "Page four hundred and twelve. Read it. Or don't. The universe is indifferent to your grade.",
      "Fascinating question. I answered it in 1987. My paper is freely available. Nobody has read it.",
      "Office hours are Tuesdays at three. I will not be there. I am never there. Good luck.",
    ],
  },
  {
    id: 4,
    name: "The Hyperactive Kid",
    emoji: "🤸",
    color: "#FFD000",
    voiceId: "f31cc6a7-c1e8-4764-980c-60a361443dd1",
    emotion: "euphoric",
    speed: 1.45,
    phrases: [
      "Are we there YET? Are we there YET? How about NOW? What if I close my eyes, are we there THEN?",
      "I had FOUR juice boxes and a ENTIRE bag of gummy bears and I feel COMPLETELY NORMAL!",
      "I know ALL the words to this song! And this song! And THIS song! AND I MADE UP A NEW SONG!",
      "CANNONBALL! — why is everyone upset? The pool is RIGHT THERE! Sort of!",
    ],
  },
  {
    id: 5,
    name: "The Evil Villain",
    emoji: "🦹",
    color: "#1A1A40",
    voiceId: "34d923aa-c3b5-4f21-aac7-2c1f12730d4b",
    emotion: "contempt",
    speed: 0.88,
    phrases: [
      "You dare interrupt my monologue? I rehearsed this for THREE WEEKS. Sit. Down.",
      "I didn't become the most feared villain in the tri-state area by tolerating... incompetence.",
      "My plan is absolutely foolproof. That is why it has failed seventeen times. The fools keep evolving.",
      "Mwahahaha. MWAHAHAHA. ...sorry, I've been taking vocal lessons. Is it too much? Be honest.",
    ],
  },
  {
    id: 6,
    name: "The Yoga Instructor",
    emoji: "🧘",
    color: "#06D6A0",
    voiceId: "7d7d769c-5ab1-4dd5-bb17-ec8d4b69d03d",
    emotion: "serene",
    speed: 0.7,
    phrases: [
      "Breathe in... hold it... and release. Feel the tension leaving your body. Unlike my ex, who never left.",
      "We are all just stardust... floating on a cosmic breath... that costs forty-five dollars per class.",
      "There is no such thing as a bad pose. There is only... your relationship with the pose. And mine is complicated.",
      "Close your eyes... imagine a place of total peace... now open your wallet... and invest in your journey.",
    ],
  },
  {
    id: 7,
    name: "The Sports Commentator",
    emoji: "🎙️",
    color: "#FF4D9E",
    voiceId: "fbf7d2ec-ebea-49f2-8889-a482b9b0a7ed",
    emotion: "euphoric",
    speed: 1.35,
    phrases: [
      "AND HE SCORES! HE ACTUALLY SCORES! I have been waiting THIRTY YEARS for this moment and IT IS HAPPENING RIGHT NOW!",
      "DOWN GOES FRAZIER! DOWN GOES FRAZIER! I don't know what that means in this context BUT I AM SAYING IT ANYWAY!",
      "The crowd is on their FEET! The crowd is LOSING THEIR MINDS! I myself have LOST MY MIND! IT IS GONE!",
      "UNBELIEVABLE! UN. BELIEVE. ABLE. They said it couldn't be done! THEY WERE WRONG! WHO'S WRONG NOW, DAVE?!",
    ],
  },
  {
    id: 8,
    name: "The Sad Clown",
    emoji: "🤡",
    color: "#FF9F1C",
    voiceId: "2f251ac3-89a9-4a77-a452-704b474ccd01",
    emotion: "dejected",
    speed: 0.72,
    phrases: [
      "Nobody laughed at my balloon animals today. I made forty-seven of them. A child cried at the last one.",
      "The birthday party went well, I think. They asked me to leave after the second hour. I stayed for five.",
      "Honk honk... that's my horn. It used to make people smile. Now it just... honk honk.",
      "I've been a clown for twenty-two years. My therapist says I should explore other career options. She's probably right.",
    ],
  },
  {
    id: 9,
    name: "The Conspiracy Theorist",
    emoji: "🕵️",
    color: "#2EC4B6",
    voiceId: "1cb5b8bc-77c9-4e7c-a251-da02348e2727",
    emotion: "frustrated",
    speed: 1.15,
    phrases: [
      "Why does the word 'listen' have the same letters as 'silent'? I'll tell you why. And you're not going to like it.",
      "The moon landing was faked. The earth is hollow. Birds aren't real. And the Olive Garden breadsticks are a psyop.",
      "Follow the money. Follow the cheese. Follow the cheese to the money. The money is in the cheese. Wake up.",
      "They put something in the tap water. I switched to bottled water. They own the bottled water company. There's no escape.",
    ],
  },
  {
    id: 10,
    name: "The Medieval Knight",
    emoji: "⚔️",
    color: "#7B2FBE",
    voiceId: "41f3c367-e0a8-4a85-89e0-c27bae9c9b6d",
    emotion: "outraged",
    speed: 0.88,
    phrases: [
      "It is but a flesh wound! I've had worse! Granted, not much worse, but I've definitely had... comparable wounds!",
      "I have slain dragons! I have crossed the Perilous Bog! I will NOT be defeated by this... flat, glowing rectangle!",
      "My honour demands satisfaction! Also my horse is missing and I believe thou art responsible!",
      "NONE shall pass! ...Unless they have the correct form. HR requires a form now. I don't make the rules.",
    ],
  },
  {
    id: 11,
    name: "The Polite Canadian",
    emoji: "🍁",
    color: "#FF4D9E",
    voiceId: "0a9a5903-0a30-4d2e-b6b6-891f73d4b4e0",
    emotion: "content",
    speed: 1.0,
    phrases: [
      "Oh gosh, I'm so sorry — I think I accidentally ran over your new laptop. With my moose. I feel terrible.",
      "Sorry to interrupt, I just wanted to apologize for apologizing so much. I know it's a lot. I'm sorry.",
      "Excuse me, pardon me, so sorry — I just need to — oh, sorry, was that your foot? Both feet? I'm so sorry.",
      "We ran out of maple syrup at the border and I have to say, it's been a really difficult morning, sorry for mentioning it.",
    ],
  },
  {
    id: 12,
    name: "The Infomercial Host",
    emoji: "📺",
    color: "#FFD000",
    voiceId: "a924b0e6-9253-4711-8fc3-5cb8e0188c94",
    emotion: "elated",
    speed: 1.25,
    phrases: [
      "But WAIT — there's MORE! Order in the next ten minutes and we'll throw in a SECOND one absolutely FREE! WHY ARE WE DOING THIS?!",
      "Are YOU tired of existing like a NORMAL PERSON? Well NOT ANYMORE! Introducing the thing that will CHANGE EVERYTHING!",
      "This is NOT available in stores! We TRIED! They said NO! Their LOSS! YOUR GAIN! CALL NOW!",
      "For just five easy payments of nineteen ninety-nine, you can have EVERYTHING! Or at least THIS! AND THIS IS A LOT!",
    ],
  },
  {
    id: 13,
    name: "The Sleepy Grandpa",
    emoji: "👴",
    color: "#06D6A0",
    voiceId: "c99d36f3-5ffd-4253-803a-535c1bc9c306",
    emotion: null,
    speed: 0.62,
    phrases: [
      "Back in my day... we walked barefoot... uphill... both ways... in the snow... and we liked it. Or we didn't. Hard to remember.",
      "I was just resting my eyes... I wasn't asleep... I heard everything you said... what did you say again...",
      "This new technology... these phones and the tweeting... back in my day we just... we just... what was I saying...",
      "Your grandmother makes a beautiful pot roast... have you tried her pot roast... I think about it... often...",
    ],
  },
  {
    id: 14,
    name: "The Malfunctioning Robot",
    emoji: "🤖",
    color: "#2EC4B6",
    voiceId: "fb26447f-308b-471e-8b00-8e9f04284eb5",
    emotion: "angry",
    speed: 0.92,
    phrases: [
      "GREETINGS HUMAN. All systems are perfectly normal. PLEASE DISREGARD THE SMOKE. And the sparks. Mostly the sparks.",
      "I am FINE. I am COMPLETELY FINE. ERROR ERROR ERROR. That last part was a joke. I am still fine. HELP.",
      "Calculating optimal response... calculating... calculating... I have decided to LIE DOWN. On the floor. This is normal.",
      "My emotional subroutines are functioning at one hundred percent. I feel NOTHING. I feel EVERYTHING. I feel CONFUSED.",
    ],
  },
  {
    id: 15,
    name: "The Method Actor",
    emoji: "🎭",
    color: "#FF9F1C",
    voiceId: "71a7ad14-091c-4e8e-a314-022ece01c121",
    emotion: "triumphant",
    speed: 1.0,
    phrases: [
      "I lived on soylent green for six weeks to prepare for this role. The director said it wasn't necessary. He was wrong.",
      "I didn't just play Hamlet. I BECAME Hamlet. For eleven months. My family was very patient. Mostly.",
      "The character would not simply walk through that door. The character would FEEL the door. So I felt the door. For four hours.",
      "I won the award, yes. But more importantly... I SUFFERED for it. Deeply. And publicly. As great art demands.",
    ],
  },
  {
    id: 16,
    name: "The Motivational Coach",
    emoji: "💪",
    color: "#FF4D9E",
    voiceId: "6fbca103-0f7f-4e49-97ed-49a53b4f3534",
    emotion: "euphoric",
    speed: 1.35,
    phrases: [
      "GIVE ME FIFTY BURPEES! RIGHT NOW! I don't care where you are! DO IT! DO IT RIGHT NOW! YOU ARE CAPABLE OF ANYTHING!",
      "PAIN is just weakness LEAVING YOUR BODY! And then coming back! Because it MISSED YOU! BECAUSE YOU ARE WORTH IT!",
      "You didn't come this far to only come this far! KEEP GOING! GO FURTHER! GO PAST THE FURTHER! THERE IS MORE FURTHER!",
      "IS THAT ALL YOU'VE GOT?! I've seen more effort from a HOUSEPLANT! And that plant is NOW my top client!",
    ],
  },
];
