// lib/characters.js
// Sentence case only — no ALL CAPS (TTS spells out acronyms).
// Short phrases. Emotionality via punctuation and emotion settings.

export const CHARACTERS = [
  {
    id: 1,
    name: "The Gruff Pirate",
    emoji: "🏴‍☠️",
    voiceId: "db69127a-dbaf-4fa9-b425-2fe67680c348",
    emotion: "outraged",
    speed: 0.82,
    phrases: ["Billions of blue blistering barnacles! Who drank me rum?!"],
  },
  {
    id: 2,
    name: "The Nervous Intern",
    emoji: "😰",
    voiceId: "f6141af3-5f94-418c-80ed-a45d450e7e2e",
    emotion: "scared",
    speed: 1.15,
    phrases: ["So... hypothetically... if someone accidentally deleted the production database... that's fixable, right? Right?"],
  },
  {
    id: 3,
    name: "The Bored Professor",
    emoji: "🎓",
    voiceId: "4f7f1324-1853-48a6-b294-4e78e8036a83",
    emotion: null,
    speed: 0.72,
    phrases: ["Page four hundred and twelve. Read it. The universe is indifferent to your grade."],
  },
  {
    id: 4,
    name: "The Hyperactive Kid",
    emoji: "🤸",
    voiceId: "f31cc6a7-c1e8-4764-980c-60a361443dd1",
    emotion: "euphoric",
    speed: 1.3,
    phrases: ["Are we there yet? Are we there yet? Are we there yet?!"],
  },
  {
    id: 5,
    name: "The Evil Villain",
    emoji: "🦹",
    voiceId: "71a7ad14-091c-4e8e-a314-022ece01c121",
    emotion: "contempt",
    speed: 0.88,
    phrases: ["You dare challenge me? I was evil before evil was cool. Now sit down."],
  },
  {
    id: 6,
    name: "The Yoga Instructor",
    emoji: "🧘",
    voiceId: "7d7d769c-5ab1-4dd5-bb17-ec8d4b69d03d",
    emotion: "serene",
    speed: 0.7,
    phrases: ["Breathe in... hold it... and release. Feel the tension leaving your body."],
  },
  {
    id: 7,
    name: "The Sports Commentator",
    emoji: "🎙️",
    voiceId: "ed81fd13-2016-4a49-8fe3-c0d2761695fc",
    emotion: "euphoric",
    speed: 1.15,
    phrases: ["Unbelievable! Absolutely unbelievable! I have never seen anything like this in my entire life!"],
  },
  {
    id: 8,
    name: "The Sad Clown",
    emoji: "🤡",
    voiceId: "3246e36c-ac8c-418d-83cd-4eaad5a3b887",
    emotion: "dejected",
    speed: 0.72,
    phrases: ["Nobody laughed at my balloon animals today. I made forty-seven of them."],
  },
  {
    id: 9,
    name: "The Conspiracy Theorist",
    emoji: "🕵️",
    voiceId: "1cb5b8bc-77c9-4e7c-a251-da02348e2727",
    emotion: "frustrated",
    speed: 1.1,
    phrases: ["Why does 'listen' have the same letters as 'silent'? I'll tell you why. And you're not going to like it."],
  },
  {
    id: 10,
    name: "The Medieval Knight",
    emoji: "⚔️",
    voiceId: "41f3c367-e0a8-4a85-89e0-c27bae9c9b6d",
    emotion: "outraged",
    speed: 0.88,
    phrases: ["I have slain dragons! I have crossed the Perilous Bog! I will not be defeated by this glowing rectangle!"],
  },
  {
    id: 11,
    name: "The Polite Canadian",
    emoji: "🍁",
    voiceId: "0a9a5903-0a30-4d2e-b6b6-891f73d4b4e0",
    emotion: "content",
    speed: 1.0,
    phrases: ["I'm so sorry — my moose accidentally ran over your laptop. I feel just terrible."],
  },
  {
    id: 12,
    name: "The Infomercial Host",
    emoji: "📺",
    voiceId: "34d923aa-c3b5-4f21-aac7-2c1f12730d4b",
    emotion: "euphoric",
    speed: 1.15,
    phrases: ["Call right now! [laughter] We will throw in a second one free! Lines are open! Why are we doing this?!"],
  },
  {
    id: 13,
    name: "The Sleepy Grandpa",
    emoji: "👴",
    voiceId: "c99d36f3-5ffd-4253-803a-535c1bc9c306",
    emotion: null,
    speed: 0.62,
    phrases: ["Back in my day... we walked barefoot... uphill... both ways..."],
  },
  {
    id: 14,
    name: "The Malfunctioning Robot",
    emoji: "🤖",
    voiceId: "fb26447f-308b-471e-8b00-8e9f04284eb5",
    emotion: "angry",
    speed: 0.92,
    phrases: ["Greetings human. All systems are perfectly normal. Please disregard the smoke."],
  },
  {
    id: 15,
    name: "The Method Actor",
    emoji: "🎭",
    voiceId: "ca31ce53-ebf6-4e51-b87d-2f65d5d1f7f8",
    emotion: "elated",
    speed: 1.05,
    phrases: ["I lived on soylent green for six weeks to prepare for this role."],
  },
  {
    id: 16,
    name: "The Motivational Coach",
    emoji: "💪",
    voiceId: "46788d8e-cdf9-4d5c-9125-094eb2e4d44c",
    emotion: "euphoric",
    speed: 1.1,
    phrases: ["Give me fifty burpees! Right now! Yes you, the Indian-looking guy!"],
  },
];
